### ISSUE TITLE
mingw and SSE/AVX

### ISSUE THREAD

**Issue by pepeverde9** [davisking/dlib#849] opened 2017-09-29 09:30 UTC
Hello
I am writing an application using  object detection from dlib.
It's not ready, but the part written is based mainly on the example train_object_detector.
It works as expected on linux (lubuntu 14.04, lubuntu 16.04, kubuntu 17.04).
But under Windows, using QT5.9 with mingw530_32 (which identifies itself as gcc 5.3.0), as soon as I set -march=native, or -march=sandybridge, or -msse2, the application crashes, currently at the second call of dlib::load_image, on windows7_64 on an I5-2500, and also on windows10_64 on an I5-7200U in release mode. The same code works in debug mode.
Also the example train_object_detector itself crashes when compiled under these conditions, using the same compiler and cmake-gui/cmake.
Has anybody used mingw with fhog training and SSE/AVX?

**Comment by davisking** [comment] 2017-09-29 10:25
It's probably because thread support in mingw is wacked.  Try running it without threads and it should run fine.  Do this by setting the number of threads to 0 and you will see what I mean.  By default, mingw doens't support C++11 threads and there is all this nonsense on the internet about how to get it to work.  But it sure doesn't seem to work well even when you get a version of mingw that supposedly supports threads.

**Comment by e-fominov** [comment] 2017-09-29 11:09
@pepeverde9 , i am using MinGW a lot (SSE2, AVX, AVX2) - all fine, but I am using x64 code. I am using all functions and training FHOG too. I had some problems with MinGW 32 bit a year ago, first was threads - but it was fixed when using SJLJ version of MinGW, the second problem is calling MinGW-compiled DLL from MSVC, it was solved with -mstackrealign flag  (the 6.3 compiler does not have this issue)

MinGW works much better in terms of performance for FHOG compared with MSVC, the other option is CLang, it works good too and compatible with MSVC libraries

**Comment by davisking** [comment] 2017-09-29 11:19
Yeah, the issue seems to only happen in the 32bit version of mingw.  I tried 32bit SJLJ this morning and got the same error as @pepeverde9.

**Comment by davisking** [comment] 2018-08-03 17:18
Closing this issue because we aren't able to reproduce it and the poster seems to have vanished.

**Closed by davisking** 2018-08-03 17:18 UTC

**Comment by pepeverde9** [comment] 2020-11-29 19:53
I forgot about this thread, and used linux for the application for some time.
Then, when a LTS Qt version came out compiled with mingw64 7.3, I could build and run the program on windows without issues using that compiler.
