### ISSUE TITLE
Failed build shape_predictor.cpp.o

### ISSUE THREAD

**Issue by herleeyandi** [davisking/dlib#958] opened 2017-11-15 04:01 UTC
Hello I am trying install dlib in ubuntu 15 then got this error. I am using python 2.7, compiled with cuda 8.0.

```
/tmp/pip-build-yr08x2hd/dlib/dlib/../dlib/image_processing/../image_transforms/../threads/parallel_for_extension.h:255:10: error: ‘void dlib::parallel_for(dlib::thread_pool&, long int, long int, const T&, long int) [with T = dlib::shape_predictor_trainer::make_regression_tree(dlib::thread_pool&, std::vector<dlib::shape_predictor_trainer::training_sample<feature_type> >&, const std::vector<dlib::vector<float, 2l> >&) const [with feature_type = unsigned char]::<lambda(long unsigned int)>]’, declared using local type ‘const dlib::shape_predictor_trainer::make_regression_tree(dlib::thread_pool&, std::vector<dlib::shape_predictor_trainer::training_sample<feature_type> >&, const std::vector<dlib::vector<float, 2l> >&) const [with feature_type = unsigned char]::<lambda(long unsigned int)>’, is used but never defined [-fpermissive]

     void parallel_for (

          ^

CMakeFiles/dlib_.dir/build.make:398: recipe for target 'CMakeFiles/dlib_.dir/src/shape_predictor.cpp.o' failed

make[2]: *** [CMakeFiles/dlib_.dir/src/shape_predictor.cpp.o] Error 1

CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/dlib_.dir/all' failed

make[1]: *** [CMakeFiles/dlib_.dir/all] Error 2

Makefile:127: recipe for target 'all' failed

make: *** [all] Error 2

error: cmake build failed!

----------------------------------------
Cleaning up...
Command /usr/bin/python3.5 -c "import setuptools, tokenize;__file__='/tmp/pip-build-yr08x2hd/dlib/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-fnvajdvk-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip-build-yr08x2hd/dlib
Storing debug log for failure in /home/mspl/.pip/pip.log
```

**Comment by herleeyandi** [comment] 2017-11-15 04:06
I just see, so dlib 19 is not working on python 2.7?

**Comment by davisking** [comment] 2017-11-15 10:38
What are the exact steps to reproduce this issue?  What do I have to type
in a terminal to make it happen?

**Comment by herleeyandi** [comment] 2017-11-15 11:07
I forget for it first command. Then I am using `pip install dlib` then it still produce same error.
![image](https://user-images.githubusercontent.com/2309538/32832969-335bfd3c-ca38-11e7-9299-8a042838d603.png)

**Comment by herleeyandi** [comment] 2017-11-15 11:19
I try dlib 18 and it still OK, just have issue in version 19.
![image](https://user-images.githubusercontent.com/2309538/32833440-e027cf4a-ca39-11e7-9ce9-6e50cd0bd8e8.png)

**Comment by herleeyandi** [comment] 2017-11-15 11:33
I try build it from source using this:
```
wget http://dlib.net/files/dlib-19.6.tar.bz2
tar xvf dlib-19.6.tar.bz2
cd dlib-19.6/
mkdir build
cd build
cmake ..
cmake --build . --config Release
sudo make install
sudo ldconfig
cd ..
pkg-config --libs --cflags dlib-1

```
I successfully build it but I can't import it in python.
![image](https://user-images.githubusercontent.com/2309538/32833962-a4a914ea-ca3b-11e7-8954-a4c39b207071.png)
![image](https://user-images.githubusercontent.com/2309538/32834000-cbb87b20-ca3b-11e7-8bed-0af5d4f75449.png)
![image](https://user-images.githubusercontent.com/2309538/32834020-e6933584-ca3b-11e7-84b7-c469c2e04c0b.png)

**Comment by davisking** [comment] 2017-11-15 12:03
Don't post screenshots.  Post text.

Also, to install from source for *python* you run `python setup.py install`

**Comment by davisking** [comment] 2018-08-03 17:21
Closing this issue because we aren't able to reproduce it and the poster seems to have vanished.

**Closed by davisking** 2018-08-03 17:21 UTC
