### ISSUE TITLE
Use installed dlib when compiling python extension.

### ISSUE THREAD

**Issue by arrowd** [davisking/dlib#876] opened 2017-10-15 15:18 UTC
Is there any reason to statically compile-in whole dlib into python extension library? I'm not against compiling stuff twice, but when I compile python extension and there is already dlib installed, the extension picks up config.h header of the installed one. This leads to inconsistency with options handling.

For instance, if dlib was compiled with PNG support, and the extension is being compiled without it, the PNG feature would be enabled anyways, because config.h installed by dlib has DLIB_PNG_SUPPORT defined.

**Comment by davisking** [comment] 2017-10-15 15:33
The dlib python build scripts should totally ignore any installed copy of dlib.  Are you saying that isn't what is happening?

**Comment by arrowd** [comment] 2017-10-15 16:38
Yep, this is what happens:

Scanning dependencies of target dlib_
make -f CMakeFiles/dlib_.dir/build.make CMakeFiles/dlib_.dir/build
[ 84%] Building CXX object CMakeFiles/dlib_.dir/src/matrix.cpp.o
/usr/bin/c++  -DDLIB_NO_ABORT_ON_2ND_FATAL_ERROR -DDLIB_VERSION=19.6.0 -Ddlib__EXPORTS -I/usr/local/include -I/usr/local/include/python2.7 -I/wrkdirs/usr/ports/science/py-dlib/work/dlib-19.6/dlib/.. -O2 -pipe -fstack-protector -fno-strict-aliasing -std=c++11 -O3 -DNDEBUG -fPIC   -ftemplate-depth=500 -DDLIB_JPEG_SUPPORT -DDLIB_PNG_SUPPORT -std=gnu++11 -o CMakeFiles/dlib_.dir/src/matrix.cpp.o -c /wrkdirs/usr/ports/science/py-dlib/work/dlib-19.6/tools/python/src/matrix.cpp
In file included from /wrkdirs/usr/ports/science/py-dlib/work/dlib-19.6/tools/python/src/matrix.cpp:4:
In file included from /usr/local/include/dlib/python.h:6:
In file included from /usr/local/include/dlib/python/boost_python_utils.h:9:
In file included from /usr/local/include/dlib/serialize.h:142:
In file included from /usr/local/include/dlib/algs.h:110:
In file included from /usr/local/include/dlib/assert.h:6:
/usr/local/include/dlib/config.h:19:9: warning: 'DLIB_JPEG_SUPPORT' macro redefined [-Wmacro-redefined]
#define DLIB_JPEG_SUPPORT
        ^
<command line>:5:9: note: previous definition is here
#define DLIB_JPEG_SUPPORT 1
        ^

**Comment by davisking** [comment] 2017-10-15 17:18
Have you edited any of the dlib files?  Also, what exactly did you type to get these messages?

**Comment by arrowd** [comment] 2017-10-15 17:23
No changes to dlib sources. I just installed dlib into /usr/local/ prefix first, and then tried to build python extension.

**Comment by davisking** [comment] 2017-10-15 17:24
What did you type?

**Comment by davisking** [comment] 2017-10-15 17:25
Maybe I should say this another way.  This doesn't happen to me.  What are the steps to reproduce the problem?

**Comment by arrowd** [comment] 2017-10-15 19:54
Well,

1. Configure dlib with, say `-DDLIB_GIF_SUPPORT=1` and all other features `=0`
2. Build it, install it into `/usr/local`.
3. `config.h` with `#define DLIB_GIF_SUPPORT` ends up in `/usr/local/include/dlib`
4. Build python extension with `--yes DLIB_GIF_SUPPORT` and all other features with `--no`.
5. Get warnings shown above during compilation.

This means that `/usr/local/include/dlib/config.h` gets picked when building python extension.

**Comment by davisking** [comment] 2017-10-15 20:08
I'm closing this since you are refusing to post the commands you used.

**Closed** 2017-10-15 20:07 UTC

**Comment by arrowd** [comment] 2017-10-15 20:21
Ok, there are exact steps:

- `cmake -DDLIB_GIF_SUPPORT=1 /path/to/dlib/source`
- `make`
- `make install`
- `cd /path/to/dlib/source`
- `python2 setup.py --yes DLIB_GIF_SUPPORT`

At the last stage, when compilation gets to `dlib_` target, I get warnings about macro redefinition. Hope this helps.

And your attitude is rude.

**Comment by davisking** [comment] 2017-10-15 20:26
I'm not being rude.  I get a huge number of vague questions like this all the time, many of which are ultimately user error.  For all I knew you were copying files around with cp and modifying paths.  Who knows.

Anyway, what OS?  I did this on ubuntu hours ago and the python build scripts did not pick up anything from /usr/local even though dlib was installed there.

**Comment by arrowd** [comment] 2017-10-15 20:44
The OS is FreeBSD. Note `-I/usr/local/include` at my compile line. Do you have it? I think it's the culprit. This include dir comes from using gif/png/jpeg, as they are also installed into `/usr/local` on FreeBSD. So, `${GIF_INCLUDE_DIR}` contains `/usr/local/include`, it gets appended to includes search path, and this causes `#include <dlib/config.h>` to be resolved against it.

What if you try installing dlib into `/usr` prefix on your Ubuntu? I think you should be ale to reproduce this.

**Comment by davisking** [comment] 2017-10-15 21:02
See, this is what I'm talking about :)

How is `-I/usr/local/include` on your compile line if you are using the unmodified python build scripts?  

Post an entire set of console commands, start to finish, that causes this problem to appear.

**Comment by arrowd** [comment] 2017-10-16 04:12
It comes from giflib includes. It is installed into `/usr/local` on my system, its includes end up in `/usr/local/include`, so `find_package(GIF)` sets `GIF_INCLUDE_DIR` to `/usr/local/include` and that path gets appended to dlib's compilation line: https://github.com/davisking/dlib/blob/master/dlib/CMakeLists.txt#L329

**Comment by davisking** [comment] 2017-10-16 10:51
I suspect it's not GIF, but one of the include path statements in https://github.com/davisking/dlib/blob/master/dlib/cmake_utils/add_python_module.  I just updated add_python_module to mark those includes as system dependencies, and so that might fix this problem.  Can you update from github and try again?

As an aside, why are you installing dlib before building the python API?  Are you using dlib in a C++ project as well?

**Comment by arrowd** [comment] 2017-10-16 19:36
> I just updated add_python_module to mark those includes as system dependencies, and so that might fix this problem. Can you update from github and try again?

I thought just the same thing today at $WORK. I've tried with your patch and it indeed fixes the issue - `-isystem` gets prepended before `-I/usr/local/include` and warnings are gone.

Thanks for working on this!

> As an aside, why are you installing dlib before building the python API? Are you using dlib in a C++ project as well?

I'm just packaging dlib for FreeBSD. While official binary packages are compiled in isolated environments, users still able to compile everything on their own using FreeBSD Ports, and they can possibly have C++ dlib installed when compiling python extension.

**Comment by davisking** [comment] 2017-10-16 19:47
No problem.  Thanks for reporting the issue.

Cool.  Make sure you link it against libx11-dev as well.  Some package managers have compiled dlib without X11 support and users regularly complain about that.

**Comment by arrowd** [comment] 2017-10-21 12:42
> Make sure you link it against libx11-dev as well. Some package managers have compiled dlib without X11 support and users regularly complain about that.

I made it an option and set default to on.

While at it, what BLAS implementation would you recommend to use with dlib? FreeBSD defaults to netlib, but dlib searches for `cblas_ddot` symbol in BLAS library, and netlib doesn't seem to have it. Then I switched to OpenBLAS and it worked.

**Comment by davisking** [comment] 2017-10-21 14:04
IntelMKL is the best, but among open source ones I would generally go with OpenBLAS.  Although you should run the entire dlib unit test suite to make sure the OpenBLAS you are using isn't messed up.  I regularly encounter package managers that have included versions of BLAS that fail to do things like compute a correct eigenvalue decomposition.  These failures are usually detected by dlib's unit test suite.  

I also often get questions from users who are running dlib and getting the wrong results because of a broken BLAS library they got from a package manager.  So please do check before making the packages available. :)
