### ISSUE TITLE
facelandmarks without detector

### ISSUE THREAD

**Issue by kwasek83** [davisking/dlib#1758] opened 2019-05-05 18:50 UTC
We are developing project where we need to set landmarks on frontal pose (0 degrees), left profile (90 degrees) and middle pose (45 degrees). DLIB out of the box has very good front face detector, but luck of the 2 more that we need. 
Our images that will be uploaded for lanmarking are standarized eg. whole face on white background. In theory we do need a detector to detect face, because face is the only item on the image. Being said that it will be easier (if possible) to force dlib to skip  detector and try to use only shape predictor. Otherwise we need to develop profile detector and middle detector which is bigger thing to do... Is it possible?
If anybody can give any hint I will be more than greatfull...

**Comment by xsacha** [comment] 2019-05-20 19:35
Duplicate of #1757
Train a new detector with other poses.

**Closed** 2019-07-05 08:00 UTC
