### ISSUE TITLE
How to free GPU memory completely

### ISSUE THREAD

**Issue by giddyyupp** [davisking/dlib#1136] opened 2018-02-15 17:45 UTC
Hi,

i wonder how to completely free net objects. for instance in the face detection example:  

// And finally we load the DNN responsible for face recognition.  
anet_type net;  
deserialize("dlib_face_recognition_resnet_model_v1.dat") >> net;  

how can i free **net** object? thanks  

source code:  
https://github.com/davisking/dlib/blob/master/examples/dnn_face_recognition_ex.cpp

**Comment by davisking** [comment] 2018-02-15 21:02
The destructor of the net object frees its resources.

**Comment by giddyyupp** [comment] 2018-02-15 21:59
yes, but since i am using VS and it is really hard to trace. add_layer, add_loss_layer? 
what is their type?

**Comment by giddyyupp** [comment] 2018-02-17 13:47
well, lets continue from the first point. and i am using version 19.8 by the way.
explicitly i can only call this destructor (afaik) and which fails in two different ways accordingly:
**net.~add_loss_layer();**   

1. if i had run a detection using something like that:
**net(face_chip);** and then i call the prev destructor, it fails in the **matrix_data_layout.h** line **287** it can't deallocate array. and this array is from detection. it belongs to **net.temp_label** variable. by the way **net.clean()** is not cleaning this **temp_label** var. why?

2. lets say if i called destructor right after I deserialized **net** object. then it fails in the memory where **static_assert(0 < sizeof (_Ty), "can't delete an incomplete type");** and here i can see all the **net.subnetwork** var. 

so can you please express what is the proper way to delete and free my gpu memory. thanks in advance.

**Comment by davisking** [comment] 2018-02-17 14:12
You don't call destructors in C++.  You need to read a book about C++ programming since you should really know not to do this. In C++ objects are automatically destructed when they go out of scope. Do not call destructors explicitly.  And certainly do not call some random destructor from somewhere in an object's inheritance hierarchy, that is an outright error.

**Closed by davisking** 2018-02-17 14:12 UTC

**Comment by giddyyupp** [comment] 2018-02-17 15:47
since i need to solve this problem i briefly ignore your claims.
so lets look at this example. if i call funcA in anywhere, after funcA returns, net object gets destructed and frees completely right? 

`void funcA(){  
anet_type net;  
deserialize("dlib_face_recognition_resnet_model_v1.dat") >> net;  
// blalalall  
}  
`

**Comment by davisking** [comment] 2018-02-17 16:44
Yes, that's how it works.

**Comment by giddyyupp** [comment] 2018-02-17 17:24
perfect, thanks. but i have some observations, let me explain.

as in the previous comment, the expected behavior is to claiming all the gpu memory back. but in reality it isn't the case. and also similar situations occurs when i create pointers to object then call delete manually.

Before loading net object, i have **279 MB** memory in use. after i load net, memory consumption goes to **483**, and after func returns it drops to **436**.  exactly same thing applies to pointers. this seems to leak but i guess not, since if i call this func in a loop,  memory consumption stays same. so maybe you are using static objects? if so, is there a way to change them.

**Comment by davisking** [comment] 2018-02-17 19:07
The NVIDIA CUDA runtime itself has static resources associated with it.
There are also certain static resources associated with certain aspects of
cuDNN. These are not memory leaks.

**Comment by giddyyupp** [comment] 2018-02-17 19:19
hmm, this may be the case but i dont think so, since i am using frequently caffe, darknet and tensorflow also, and whenever i delete my network i can get all the used memory back. but here i am not. could you please check it again and verify. because in my first example i didnt even feed the network with a single image, so there is no cudnn and nothing and also after i delete my network there should not be any cuda involved.

and please reopen this issue, and i am really wondering is there anyone who uses dlib in production, whether faced with this problem or not. or all of them just uses it with for their personal purposes.

**Comment by davisking** [comment] 2018-02-17 19:46
Then you must be using caffe in a manner that causes the cuda runtime to be
unloaded, like by spawning a subprocess that is eventually terminated. To
see what I'm talking about all you need to do is write a program that calls
cudaMalloc(), then frees the memory via cudaFree(). You will see that the
process still uses GPU memory afterwards. This is not a bug or issue in
CUDA, it's how it works and it's fine.

Yes, many people use dlib in production.  The primary audience for dlib is
professional C++ developers who use ML in production.
