### ISSUE TITLE
convert_dlib_nets_to_caffe

### ISSUE THREAD

**Issue by scott-vsi** [davisking/dlib#803] opened 2017-09-05 14:12 UTC
I've noticed a problem with convert_dlib_nets_to_caffe/main.cpp. I have a deep network that uses a max_pool layer with a padding of 1 (a kernel of 3 and a stride of 2). When I try to encode an image with the converted network in caffe I get a (significantly) different encoding compared to encoding the image with dlib.

I see that you have to convert between how caffe and dlib handle padding in compute_caffe_padding_size_for_pooling_layer(). For my network, this function sets the padding at 0 so that the output sizes are consistent. However, this results in a max_pool layer that pools over different sets of pixels. (I know that in this case it is only a single pixel shift, but surprisingly this has a significant impact on the final encoding.)

I was able to fix this by leaving the padding at 1 and inserting a Crop layer after the max_pool layer (and fixing the top pointers, etc.) to set the output size back to the shape expected by dlib.

I'm not sure if this would work in general, but perhaps compute_caffe_padding_size_for_pooling_layer() should print a warning if pad != padding.

**Comment by davisking** [comment] 2017-09-05 14:16
Yeah, it's confusing.  None of this stuff is documented in caffe.  I had to dig around in their code and test things to find the corner cases.  I'm not surprised there are other weird cases I missed.  

But in any case, the output from the networks should be the same.  So the fix for this is either to make it a hard error, or to modify things as you did to make it work.  If you think your change is a general fix then please submit it as a PR :).  Or if not, submit a PR that makes the conversion an error.

**Closed** 2017-11-19 20:17 UTC

**Comment by headupinclouds** [comment] 2018-03-25 16:04
@scott-vsi : Can you share your pad + crop layer fix (or workaround)?  I guess I'm trying to reproduce what you have already done in a small dlib -> xml -> caffe conversion sample (based on a dlib tutorial) and am encountering similar issues.  

Test project: https://github.com/headupinclouds/hunter_dlib_ncnn#convert-model-to-caffe-format-using-dlib-tools

For what it's worth, it looks like there will be an official `floor()` conversion added to caffe soon in this PR https://github.com/BVLC/caffe/pull/3057.

**Comment by scott-vsi** [comment] 2018-03-26 18:15
I didn't actually make any code changes because it wasn't clear that it was the correct thing to _always_ do. 

Instead, I manually edited the prototxt file to set the padding of the MaxPool layer to 1 (as it was in the Dlib model). The problem with that, however, is the output layer is now a different shape. Fortunately, It is simply a single row/col too big, so I inserted a CropLayer after the MaxPool layer to bring the output layer back to the correct size (this required fixing up the top/bottom pointers to the adjacent layers, of course).

After doing this, I was able to get the same encodings in Caffe as I got in Dlib.

I've included the relevent layers:

```
layer {
  name: "max_pool375"
  type: "Pooling"
  bottom: "relu376"
  top: "max_pool375"
  pooling_param {
    pool: MAX
    kernel_h: 3
    kernel_w: 3
    stride_h: 2
    stride_w: 2
    pad_h: 0
    pad_w: 0
  }
}
layer {
  name: "con373"
  type: "Convolution"
  bottom: "max_pool375"
  top: "con373"
  convolution_param {
    num_output: 64
    pad_h: 0
    pad_w: 0
    kernel_h: 1
    kernel_w: 1
    stride_h: 1
    stride_w: 1
  }
}
```

became:

```
layer {
  name: "max_pool375"
  type: "Pooling"
  bottom: "relu376"
  top: "max_pool375"
  pooling_param {
    pool: MAX
    kernel_h: 3
    kernel_w: 3
    stride_h: 2
    stride_w: 2
    pad_h: 1
    pad_w: 1
  }
}
layer {
  name: "crop_reference"
  type: "DummyData"
  top: "crop_reference"
  dummy_data_param {
    num: 1
    channels: 64
    height: 56
    width: 56
  }
}
layer {
  name: "crop_layer"
  type: "Crop"
  bottom: "max_pool375"
  bottom: "crop_reference"
  top: "crop_layer"
  crop_param {
    axis: 2
    offset: 0
  }
}
layer {
  name: "con373"
  type: "Convolution"
  bottom: "crop_layer"
  top: "con373"
  convolution_param {
    num_output: 64
    pad_h: 0
    pad_w: 0
    kernel_h: 1
    kernel_w: 1
    stride_h: 1
    stride_w: 1
  }
}
```

**Comment by headupinclouds** [comment] 2018-04-07 17:25
@scott-vsi : Thanks for the sample.

**Comment by DariaDobro** [comment] 2018-11-28 15:33
@headupinclouds, Did you succeed to convert dlib model "dlib_face_recognition_resnet_model_v1" in caffe? I also faced this problem. It's very important for hardware acceleration, because manufacturers support only well known libraries for deep learning

**Comment by headupinclouds** [comment] 2019-01-22 15:50
@DariaDobro : I just saw this while referencing the discussion.  Sorry for the delay.  I was able to get something working using https://github.com/davisking/dlib/blob/master/tools/convert_dlib_nets_to_caffe/running_a_dlib_model_with_caffe_example.py.  In my case, I was able to get similar performance with a fully convolutional model w/ stride == 2, so I just bypassed the ceil/floor edge case altogether, which probably results in a faster model anyway.
